In [5]:
import pandas as pd

read the data

In [7]:
dataset=pd.read_csv('/content/adult.csv')
dataset

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28850,25,Private,66935,HS-grad,9,Never-married,Craft-repair,Not-in-family,White,Male,0.0,0.0,35.0,United-States,<=50K
28851,20,Private,344278,11th,7,Separated,Other-service,Own-child,White,Female,0.0,0.0,40.0,United-States,<=50K
28852,29,Private,108574,Assoc-voc,11,Never-married,Priv-house-serv,Own-child,White,Female,0.0,0.0,40.0,United-States,<=50K
28853,56,Private,244605,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
28854,45,Private,363677,Doctorate,16,Ma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Display the first 5 rows of the dataset.

In [8]:
dataset.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K

summary of the DataFrame

In [9]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28855 entries, 0 to 28854
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              28855 non-null  int64
 1   workclass        28855 non-null  object
 2   fnlwgt           28855 non-null  int64
 3   education        28855 non-null  object
 4   educational-num  28855 non-null  int64
 5   marital-status   28855 non-null  object
 6   occupation       28854 non-null  object
 7   relationship     28854 non-null  object
 8   race             28854 non-null  object
 9   gender           28854 non-null  object
 10  capital-gain     28854 non-null  float64
 11  capital-loss     28854 non-null  float64
 12  hours-per-week   28854 non-null  float64
 13  native-country   28854 non-null  object
 14  income           28854 non-null  object
dtypes: float64(3), int64(3), object(9)
memory usage: 3.3+ MB

descriptive statistics for numeric columns

In [10]:
dataset.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,28855.000000,2.885500e+04,28855.000000,28854.000000,28854.000000,28854.000000
mean,38.634344,1.897565e+05,10.073575,1070.827892,88.328273,40.442608
std,13.742880,1.054501e+05,2.559413,7463.025745,403.260391,12.384877
min,17.000000,1.349200e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781090e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.384100e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

Display the column names of the DataFrame.

In [11]:
dataset.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

unique values in the 'workclass' column.

In [12]:
dataset.workclass.unique()

array(['Private', 'Local-gov', '?', 'Self-emp-not-inc', 'Federal-gov',
       'State-gov', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

Create a new column 'income_binary' where <=50K is 0 and >50K is 1.

In [18]:
dataset['income_binary'] = dataset['income'].apply(lambda x: 0 if x == '<=50K' else 1)
dataset

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,income_binary
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K,0
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K,0
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K,1
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K,1
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28850,25,Private,66935,HS-grad,9,Never-married,Craft-repair,Not-in-family,White,Male,0.0,0.0,35.0,United-States,<=50K,0
28851,20,Private,344278,11th,7,Separated,Other-service,Own-child,White,Female,0.0,0.0,40.0,United-States,<=50K,0
28852,29,Private,108574,Assoc-voc,11,Never-married,Priv-house-serv,Own-child,White,Female,0.0,0.0,40.0,United-States,<=50K,0
28853,56,Private,244605,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K,0
28854,45,Private,363677,Doctorate,16,Ma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

Create a new column 'age_group' categorizing ages into 'Youth' (< 30), 'Adult' (30-60), and 'Senior' (60+).

In [19]:
dataset['age_group'] = pd.cut(dataset['age'], bins=[0, 30, 60, float('inf')], labels=['Youth', 'Adult', 'Senior'])
dataset

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,income_binary,age_group
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K,0,Youth
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K,0,Adult
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K,1,Youth
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K,1,Adult
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K,0,Youth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28850,25,Private,66935,HS-grad,9,Never-married,Craft-repair,Not-in-family,White,Male,0.0,0.0,35.0,United-States,<=50K,0,Youth
28851,20,Private,344278,11th,7,Separated,Other-service,Own-child,White,Female,0.0,0.0,40.0,United-States,<=50K,0,Youth
28852,29,Private,108574,Assoc-voc,11,Never-married,Priv-house-serv,Own-child,White,Female,0.0,0.0,40.0,United-States,<=50K,0,Youth
28853,56,Private,244605,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K,0,Adult
28854,45,Private,363677,Doctorate,16,Ma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult

Rename the 'educational-num' column to 'education_num'.

In [20]:
dataset.rename(columns={'educational-num': 'education_num'}, inplace=True)
dataset

,age,workclass,fnlwgt,education,education_num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,income_binary,age_group
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K,0,Youth
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K,0,Adult
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K,1,Youth
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K,1,Adult
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K,0,Youth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28850,25,Private,66935,HS-grad,9,Never-married,Craft-repair,Not-in-family,White,Male,0.0,0.0,35.0,United-States,<=50K,0,Youth
28851,20,Private,344278,11th,7,Separated,Other-service,Own-child,White,Female,0.0,0.0,40.0,United-States,<=50K,0,Youth
28852,29,Private,108574,Assoc-voc,11,Never-married,Priv-house-serv,Own-child,White,Female,0.0,0.0,40.0,United-States,<=50K,0,Youth
28853,56,Private,244605,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K,0,Adult
28854,45,Private,363677,Doctorate,16,Ma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Adult

Replace the missing values represented by '?' in 'workclass' and 'occupation' columns with 'Unknown'.

In [ ]:
Calculate the average age for each workclass.

In [21]:
dataset.groupby('workclass')['age'].mean()

workclass
?                   39.274926
Federal-gov         42.318072
Local-gov           41.662690
Never-worked        19.200000
Private             36.964008
Self-emp-inc        45.387129
Self-emp-not-inc    45.432292
State-gov           39.583954
Without-pay         45.333333
Name: age, dtype: float64

Find the total capital-gain for each gender.

In [22]:
dataset.groupby('gender')['capital-gain'].sum()

gender
Female     5704885.0
Male      25192783.0
Name: capital-gain, dtype: float64

Get the count of each marital-status category.

In [23]:
dataset['marital-status'].value_counts()

marital-status
Married-civ-spouse       13174
Never-married             9549
Divorced                  3927
Separated                  912
Widowed                    889
Married-spouse-absent      380
Married-AF-spouse           23
Ma                           1
Name: count, dtype: int64

Find the mean hours-per-week worked by individuals in different education levels.

In [24]:
dataset.groupby('education')['hours-per-week'].mean()

education
10th            37.652387
11th            34.269549
12th            34.407713
1st-4th         38.821429
5th-6th         39.494949
7th-8th         39.115453
9th             38.383721
Assoc-acdm      41.126350
Assoc-voc       41.532718
Bachelors       42.370527
Doctorate       46.253776
HS-grad         40.671531
Masters         43.418590
Preschool       36.576923
Prof-school     48.251599
Some-college    38.894159
Name: hours-per-week, dtype: float64

Calculate the mean, median, and standard deviation of 'fnlwgt' for each race.

In [25]:
dataset.groupby('race')['fnlwgt'].agg(['mean', 'median', 'std'])

                             mean    median            std
race
Amer-Indian-Eskimo  121731.661818  108765.0  100337.774841
Asian-Pac-Islander  159856.569444  139012.0   87768.812310
Black               232467.644203  210959.0  128375.607520
Other               196191.763948  182360.0   99052.249563
White               186722.138702  177132.5  101831.666656

Get the unique values and their counts for the 'native-country' column

In [26]:
dataset['native-country'].value_counts()

native-country
United-States                 25915
Mexico                          552
?                               497
Philippines                     166
Germany                         127
Puerto-Rico                     123
Canada                          114
India                            87
El-Salvador                      87
China                            81
Cuba                             79
England                          73
South                            70
Jamaica                          61
Dominican-Republic               59
Italy                            59
Poland                           54
Japan                            52
Haiti                            50
Guatemala                        49
Vietnam                          46
Portugal                         46
Columbia                         41
Iran                             39
Greece                           38
Taiwan                           36
Nicaragua                        27
Ecuador                          27
Peru                             25
Ireland                          24
Thailand                         20
Cambodia                         18
France                           16
Trinadad&Tobago                  15
Hong                             14
Honduras                         13
Outlying-US(Guam-USVI-etc)       13
Scotland                         12
Yugoslavia                       12
Laos                              9
Hungary                           8
Name: count, dtype: int64

Filter the dataset to include only individuals with income >50K.

In [28]:
dataset[dataset['income'] == '>50K']

,age,workclass,fnlwgt,education,education_num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,income_binary,age_group
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K,1,Youth
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K,1,Adult
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103.0,0.0,32.0,United-States,>50K,1,Senior
10,65,Private,184454,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418.0,0.0,40.0,United-States,>50K,1,Senior
14,48,Private,279724,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103.0,0.0,48.0,United-States,>50K,1,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28845,64,Private,391121,7th-8th,4,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,40.0,United-States,>50K,1,Senior
28846,42,Private,211450,Masters,14,Never-married,Exec-managerial,Not-in-family,White,Male,0.0,0.0,45.0,United-States,>50K,1,Adult
28847,44,Private,156413,Some-college,10,Married-civ-spouse,Tech-support,Husband,White,Male,0.0,0.0,44.0,United-States,>50K,1,Adult
28848,41,Private,116797,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,7298.0,0.0,50.0,United-States,>50K,1,Adult
28849,53,Local-gov,204447,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,43.0,United-States,>50K,1,Adult

Sort the dataset by age in descending order.

In [30]:
dataset.sort_values(by='age', ascending=False)

,age,workclass,fnlwgt,education,education_num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,income_binary,age_group
20390,90,?,256514,Bachelors,13,Widowed,?,Other-relative,White,Female,991.0,0.0,10.0,United-States,<=50K,0,Senior
22905,90,Private,313986,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K,0,Senior
17321,90,Private,137018,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0.0,0.0,40.0,United-States,<=50K,0,Senior
26826,90,Private,175491,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,9386.0,0.0,50.0,Ecuador,>50K,1,Senior
20351,90,Private,313986,11th,7,Never-married,Handlers-cleaners,Own-child,White,Male,0.0,0.0,40.0,United-States,<=50K,0,Senior
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26576,17,Private,228399,11th,7,Never-married,Other-service,Own-child,White,Female,0.0,0.0,7.0,United-States,<=50K,0,Youth
17121,17,Private,198124,11th,7,Never-married,Sales,Own-child,White,Male,0.0,0.0,20.0,United-States,<=50K,0,Youth
17095,17,Private,32607,10th,6,Never-married,Farming-fishing,Own-child,White,Male,0.0,0.0,20.0,United-States,<=50K,0,Youth
17085,17,Private,193830,11th,7,Never-married,Sales,Own-child,White,Female,0.0,0.0,20.0,United-States,<=50K,0,Youth
7877,17,Private,284277,11th,7,Never-married,Other-service,Own-child,White,Male,1055.0,0.0,20.0,United-States,<=50K,0,Youth

Filter the dataset to include only individuals who work more than 40 hours per week.

In [32]:
dataset[dataset['hours-per-week'] > 40]

,age,workclass,fnlwgt,education,education_num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,income_binary,age_group
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K,0,Adult
14,48,Private,279724,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103.0,0.0,48.0,United-States,>50K,1,Adult
15,43,Private,346189,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,50.0,United-States,>50K,1,Adult
19,40,Private,85019,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,45.0,?,>50K,1,Adult
20,34,Private,107914,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0.0,0.0,47.0,United-States,>50K,1,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28838,34,Private,191834,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,48.0,United-States,<=50K,0,Adult
28846,42,Private,211450,Masters,14,Never-married,Exec-managerial,Not-in-family,White,Male,0.0,0.0,45.0,United-States,>50K,1,Adult
28847,44,Private,156413,Some-college,10,Married-civ-spouse,Tech-support,Husband,White,Male,0.0,0.0,44.0,United-States,>50K,1,Adult
28848,41,Private,116797,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,7298.0,0.0,50.0,United-States,>50K,1,Adult
28849,53,Local-gov,204447,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,43.0,United-States,>50K,1,Adult

In [ ]:
Calculate the percentage of missing values in each column.

In [36]:
dataset.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital-status    0
occupation        1
relationship      1
race              1
gender            1
capital-gain      1
capital-loss      1
hours-per-week    1
native-country    1
income            1
income_binary     0
age_group         0
dtype: int64

Calculate the median income by education level and gender.

In [43]:
dataset.groupby(['education', 'gender'])['income_binary'].median()

education     gender
10th          Female    0.0
              Male      0.0
11th          Female    0.0
              Male      0.0
12th          Female    0.0
              Male      0.0
1st-4th       Female    0.0
              Male      0.0
5th-6th       Female    0.0
              Male      0.0
7th-8th       Female    0.0
              Male      0.0
9th           Female    0.0
              Male      0.0
Assoc-acdm    Female    0.0
              Male      0.0
Assoc-voc     Female    0.0
              Male      0.0
Bachelors     Female    0.0
              Male      0.0
Doctorate     Female    1.0
              Male      1.0
HS-grad       Female    0.0
              Male      0.0
Masters       Female    0.0
              Male      1.0
Preschool     Female    0.0
              Male      0.0
Prof-school   Female    0.0
              Male      1.0
Some-college  Female    0.0
              Male      0.0
Name: income_binary, dtype: float64

Find the top 3 occupations with the highest average capital-gain.

In [41]:
dataset.groupby('occupation')['capital-gain'].mean().nlargest(3)

occupation
Prof-specialty     2865.008306
Exec-managerial    2153.967606
Sales              1220.093960
Name: capital-gain, dtype: float64

Filter the dataset to include individuals who are 'Married-civ-spouse' and have an income >50K.

In [42]:
dataset[(dataset['marital-status'] == 'Married-civ-spouse') & (dataset['income'] == '>50K')]

,age,workclass,fnlwgt,education,education_num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,income_binary,age_group
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K,1,Youth
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K,1,Adult
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103.0,0.0,32.0,United-States,>50K,1,Senior
10,65,Private,184454,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418.0,0.0,40.0,United-States,>50K,1,Senior
14,48,Private,279724,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103.0,0.0,48.0,United-States,>50K,1,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28841,34,Private,303187,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0.0,0.0,40.0,?,>50K,1,Adult
28845,64,Private,391121,7th-8th,4,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,40.0,United-States,>50K,1,Senior
28847,44,Private,156413,Some-college,10,Married-civ-spouse,Tech-support,Husband,White,Male,0.0,0.0,44.0,United-States,>50K,1,Adult
28848,41,Private,116797,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,7298.0,0.0,50.0,United-States,>50K,1,Adult
28849,53,Local-gov,204447,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,43.0,United-States,>50K,1,Adult